demo/urls.py
from django.contrib import admin
from django.urls import path

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('department/index', views.index, name='department-index'),
    path('department/add', views.add, name='department-add'),
    path('department/destroy/<int:id>', views.destroy, name='department-destroy'),
    path('department/update/<int:id>', views.update, name='department-update'),

    path('userinfo/index', views.userinfo_index, name='userinfo-index'),
    path('userinfo/add', views.userinfo_add, name='userinfo-add'),
    path('userinfo/destroy/<int:id>', views.userinfo_destroy, name='userinfo-destroy'),
    path('userinfo/update/<int:id>', views.userinfo_update, name='userinfo-update')

]

app/models.py
from django import forms
from django.db import models


# Create your models here.
class Department(models.Model):
    name = models.CharField(verbose_name='名称', max_length=255, null=True)

    def __str__(self):
        return self.name


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入部门名称'})
        }


class Userinfo(models.Model):
    GENDER_CHOICES = (
        (1, '男'),
        (2, '女'),
        (3, '保密'),
    )

    username = models.CharField(verbose_name='用户名', max_length=255)
    password = models.CharField(verbose_name='密码', max_length=64)
    gender = models.SmallIntegerField(verbose_name='性别', choices=GENDER_CHOICES,
                                      default=GENDER_CHOICES[2][0])
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now=True)
    department = models.ForeignKey('Department', on_delete=models.CASCADE)


class UserinfoForm(forms.ModelForm):
    class Meta:
        model = Userinfo
        fields = ['username', 'password', 'gender', 'department']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入姓名'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入密码'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'department': forms.Select(attrs={'class': 'form-control'})
        }


class PrettyNum(models.Model):
    LEVEL_CHOICES = (
        (1, '一级'),
        (2, '二级'),
        (3, '三级'),
        (4, '四级'),
    )
    STATUS_CHOICES = (
        (1, '已使用'),
        (2, '未使用'),
    )

    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.IntegerField(verbose_name='价格', default=0)
    level = models.SmallIntegerField(
        verbose_name='等级', choices=LEVEL_CHOICES, default=1)
    status = models.SmallIntegerField(
        verbose_name='状态', choices=STATUS_CHOICES, default=2)

app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from app.models import DepartmentForm, Department, UserinfoForm, Userinfo


# Create your views here.
def index(request):
    departments = Department.objects.all()
    return render(request, 'department/index.html', {'departments': departments})


def add(request):
    if request.method != 'POST':
        department = DepartmentForm()
        return render(request, 'department/add.html', {'from': department})

    department = DepartmentForm(request.POST)
    if not department.is_valid():
        return render(request, 'department/add.html', {'from': department})

    department.save()
    return redirect('department-index')


def update(request, id):
    department = Department.objects.filter(id=id)
    if request.method != 'POST':
        return render(request, 'department/update.html', {'department': department.first()})

    department.update(name=request.POST.get('name'))

    return redirect('department-index')


def destroy(request, id):
    deleted, _ = Department.objects.filter(id=id).delete()

    if deleted:
        return redirect('department-index')


def userinfo_add(request):
    if request.method != 'POST':
        user_form = UserinfoForm()
        return render(request, 'userinfo/add.html', {'from': user_form})

    user_info = UserinfoForm(request.POST)
    if not user_info.is_valid():
        return render(request, 'userinfo/add.html', {'from': user_info})

    user_info.save()
    return redirect('userinfo-index')


def userinfo_index(request):
    users = Userinfo.objects.all()

    return render(request, 'userinfo/index.html', {'users': users})


def userinfo_destroy(request, id):
    deleted, _ = Userinfo.objects.filter(id=id).delete()

    if deleted:
        return redirect('userinfo-index')


def userinfo_update(request, id):
    userinfo = Userinfo.objects.filter(id=id).first()
    if request.method == 'GET':
        form = UserinfoForm(instance=userinfo)

        return render(request, 'userinfo/update.html', {'form': form})

    form = UserinfoForm(data=request.POST, instance=userinfo)
    if form.is_valid():
        form.save()
        return redirect('userinfo-index')
    return render(request, 'userinfo/update.html', {"form": form})

templates/department/add.html
{% extends 'layout/layout.html' %}

{% block content %}
    <form class="row g-3 needs-validation" novalidate method="post">
        {% csrf_token %}
        {% for field in from %}
        	<div class="col-md-12">
            <label class="form-label">{{ field.label }}</label>
                {{ field }}
                {{ field.errors.0 }}
{#            <input type="text" name="name" class="form-control" placeholder="输入部门名称"/>#}
        </div>
        {% endfor %}
        <div class="col-12">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
{% endblock %}

templates/department/index.html
{% extends 'layout/layout.html' %}

{% block content %}
    <a href="{% url 'department-add' %}" class="btn btn-primary">添加部门</a>
    <table class="table">
        <thead>
        <tr>
            <td>ID</td>
            <td>部门名称</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody>
        {% for department in  departments %}
            <tr>
                <th>{{ department.id }}</th>
                <td>{{ department.name }}</td>
                <td>
                    <a href="{% url 'department-update' department.id %}" class="btn btn-primary">编辑</a>
                    <a href="{% url 'department-destroy' department.id %}" class="btn btn-danger">删除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/department/update.html
{% extends 'layout/layout.html' %}

{% block content %}
    <form class="row g-3 needs-validation" novalidate method="post">
        {% csrf_token %}

        <div class="col-md-12">
            <label class="form-label">部门名称</label>
            <input type="text" name="name" class="form-control" value="{{ department.name }}"/>
        </div>

        <div class="col-12">
            <button class="btn btn-primary" type="submit">更新</button>
        </div>
    </form>
{% endblock %}

templates/layout/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">练习管理系统</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'department-index' %}">部门管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userinfo-index' %}">用户管理</a>
                </li>
            </ul>

        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.3/js/bootstrap.js"></script>
</html>

templates/userinfo/add.html
{% extends 'layout/layout.html' %}

{% block content %}
    <form class="row g-3 needs-validation" novalidate method="post">
        {% csrf_token %}
        {% for field in from %}
        	<div class="col-md-12">
            <label class="form-label">{{ field.label }}</label>
                {{ field }}
                <span style="color: red">{{ field.errors.0 }}</span>
{#            <input type="text" name="name" class="form-control" placeholder="输入部门名称"/>#}
        </div>
        {% endfor %}
        <div class="col-12">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
{% endblock %}

templates/userinfo/index.html
{% extends 'layout/layout.html' %}

{% block content %}
    <a href="{% url 'userinfo-add' %}" class="btn btn-primary">添加用户</a>
    <table class="table">
        <thead>
        <tr>
            <td>ID</td>
            <td>用户名</td>
            <td>密码</td>
            <td>性别</td>
            <td>部门</td>
            <td>添加时间</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody>
        {% for user in  users %}
            <tr>
                <th>{{ user.id }}</th>
                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.get_gender_display }}</td>
                <td>{{ user.department.name }}</td>
                <td>{{ user.create_time|date:'Y-m-d H:i:s' }}</td>
                <td>
                    <a href="{% url 'userinfo-update' user.id %}" class="btn btn-primary">编辑</a>
                    <a href="{% url 'userinfo-destroy' user.id %}" class="btn btn-danger">删除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/userinfo/update.html
{% extends 'layout/layout.html' %}

{% block content %}
    <form class="row g-3 needs-validation" novalidate method="post">
        {% csrf_token %}
        {% for field in form %}
        	<div class="col-md-12">
            <label class="form-label">{{ field.label }}</label>
                {{ field }}
                <span style="color: red">{{ field.errors.0 }}</span>
{#            <input type="text" name="name" class="form-control" placeholder="输入部门名称"/>#}
        </div>
        {% endfor %}
        <div class="col-12">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
{% endblock %}